### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by UnknownKoreanSmiley** [lzls/Videos#14]
JNI DETECTED ERROR IN APPLICATION: JNI NewGlobalRef called with pending exception java.lang.ClassNotFoundException: Didn't find class i face this error

**Comment by lzls** [comment]
What's class? Please paste the detailed error log to me

**Comment by lzls** [comment]
This probably has been resolved. See commit [94805e7](https://github.com/lzls/Videos/commit/94805e7a5c3642fa8e561439d11d58ed637ccc8a).

**Comment by lzls** [comment]
@UnknownKoreanSmiley ?

**Comment by UnknownKoreanSmiley** [comment]
> @UnknownKoreanSmiley ?

ohh sorry please,i didn't get notification,i thought you forgot,can u check your gmail

**Comment by lzls** [comment]
> > @UnknownKoreanSmiley ?
> 
> ohh sorry please,i didn't get notification,i thought you forgot,can u check your gmail

OK. I saw your email attached log. It's because you probably have changed the package name to `com.dev.videos`. Unfortunately, the `libvideos.so` is strongly dependent on the package name `com.liuzhenlin.videos`. To solve this, you can simply modify the native methods in [SophixAppStub.java](https://raw.githubusercontent.com/lzls/Videos/release/app/src/main/java/com/liuzhenlin/videos/SophixAppStub.java) and [AESUtils.java](https://raw.githubusercontent.com/lzls/Videos/dev/common/src/main/java/com/liuzhenlin/common/utils/AESUtils.java) with your own java-level implementations and do not load the so file.
